* Emacs on windows

some useful stuff https://www.gnu.org/software/emacs/manual/html_mono/efaq-w32.html#Location-of-init-file

install emacs from here - http://ftp.task.gda.pl/pub/gnu/emacs/windows/emacs-27/

set home path variable like the guy in this tut - https://lucidmanager.org/productivity/emacs-windows/

do - setx HOME %USERPROFILE% in windows powershell

then you will see that HOME variable has appeared under - settings -> system -> advanced system settings -> environment variables 

then open emacs and do C-h v, write user-emacs-directory and enter. It will create an .emacs.d directory under HOME path. 

It works, right? okay, now you remember how to set the path.

now go back to environment variables and make it like so - C:\Users\Arvydas\emacs

You will place the .emacs file in that folder and also .emacs.d folder will appear in it. great.

put some variables in .emacs and confirm that emacs got modified

(menu-bar-mode -1)            ; Disable the menu bar
(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips
(set-fringe-mode 10)       ; Give some breathing room

worked for me so far.

Time to link it with Dropbox.

add this to the .emacs file. right under use-package installation

(org-babel-load-file (expand-file-name "C:\\Users\\Arvydas\\Dropbox\\temp_emacs\\myinit.org"))

imesk theme i .emacs.d, jokiu folderiu. turetu veikti
* Shortcuts
1) M-g j     = Dumb jump
2) M-%       = Query replace
3) M-x flyspell = auto_correct(choose from meniu)
4) C-M i = step on a word and correct it's spelling. multiple presses for different words
5) C-c C-p I = open buffers OF THE CURRENT PROJECT
6) M-,       = Go back one step
7) C-h i     = info about your whole linux system and programs installed
8) C-h r     = info manual emacs
9) C-h m     = describe mode
10) C-h k    = describe key
11) C-x n s  = narrow down to one headline in org mode
12) C-x n w  = widen back to normal
13) C-c u    = undo tree visualize
14) M-x highlight-regexp = highlights word occurences in the buffer
15) C-x h    = mark buffer
16) C-x SPC  = rectangle mode
17) C-u c-u c-u . = enter current date timestamp - this puts to agenda
18) C-c .    = enter current date timestamp same
19) C-c !    = enter current date timestamp BUT no agenda entry
20) C-x (    = define macro - do a sequence
21) C-x )    = stop defining
22) C-x e    = executes macro
23) C-SCP x2 = makes a mark
24) C-x C-SCP = jumps to that mark
25) C-x r SCP <any> = resgister a key(position)
26) C-x r j <any> = jump to the key(to that position)
27) C-c C-w  = refile to enother point in the org document or another file
28) C-c C-s  = schedule org item
29) C-c C-d  = set a deadine to org item

